config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'accounts#index'
  resources :accounts do
    resources :transactions, only: [:create, :new]
  end

  namespace :api do
    namespace :v1 do
      post 'accounts/new_transaction', to: 'accounts#new_transaction'
    end
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :transactions

  validates :user, presence: true
  validates :account_name, presence: true, uniqueness: true
  validates :balance, presence: true, numericality: true

  private


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  TRANSACTION_TYPES = %w[withdraw deposit].freeze
  PURPOSES = %w[rent food restaurant fun sport depts other].freeze
  belongs_to :account

  validates :account, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :transaction_type, presence: true, inclusion: { in: TRANSACTION_TYPES }
  validates :transaction_number, presence: true, uniqueness: true
  validates :purpose, presence: true, inclusion: { in: PURPOSES }, if: -> { withdraw? }

  before_validation :load_defaults

  scope :expenses_for_this_month, -> {
    where(transaction_type: 'withdraw')
      .where('created_at >= ? AND created_at <= ?', Date.today.beginning_of_month, Time.now)
  }
  scope :all_expenses, -> { where(transaction_type: 'withdraw') }
  scope :expenses_for, ->(purpose) { where(purpose: purpose).pluck(:amount) }

  def withdraw?
    return true if transaction_type == 'withdraw'
  end

  private

  def load_defaults
    return unless new_record?
    self.transaction_number = SecureRandom.uuid
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :accounts

  validates :first_name, :last_name, presence: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  def index
    @accounts = Account.where(user_id: current_user.id)
  end

  def show
    @transactions = @account.transactions.all
  end

  def new
    @account = current_user.accounts.new
  end

  def edit
  end

  def create
    @account = current_user.accounts.new(account_params)
    if @account.save
      redirect_to @account, notice: 'Account was successfully created.'
    else
      render :new
    end
  end

  def update
    if @account.update(account_params)
      redirect_to @account, notice: 'Account was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @account.destroy
    redirect_to accounts_url, notice: 'Account was successfully destroyed.'
  end

  private

  def set_account
    @account = current_user.accounts.find(params[:id])
  end

  def account_params
    params.require(:account).permit(:account_name)
  end
end

app/controllers/api/v1/accounts_controller.rb
module Api
  module V1
    class AccountsController < ApplicationController
      skip_before_action :verify_authenticity_token
      def new_transaction
        amount            = params[:amount].try(:to_f)
        transaction_type  = params[:transaction_type]
        purpose           = params[:purpose]
        account_id        = params[:account_id]

        errors = Accounts::ValidateNewTransaction.new(
          amount: amount,
          transaction_type: transaction_type,
          account_id: account_id,
          purpose: purpose
        ).execute!

        if errors.any?
          render json: { errors: errors }, status: 402
        else
          account = Accounts::PerformTransaction.new(
            amount: amount,
            transaction_type: transaction_type,
            account_id: account_id,
            purpose: purpose
          ).execute!

          render json: { balance: account.balance }
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  http_basic_authenticate_with name: ENV['BASIC_AUTH_NAME'], password: ENV['BASIC_AUTH_PASSWORD'] if Rails.env.production?
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def transactions_of_all_time
    render json: Transaction.group(:amount).count
  end

  def transactions_of_this_month
    render json: Transaction.created_between(Date.today.beginning_of_month, Time.now).group(:purpose).count
  end
end
 

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_account, only: [:new, :create]

  def new
    @transaction = @account.transactions.new
  end

  def create
    @transaction = @account.transactions.new(transaction_params)
    if @account.save
      redirect_to @account, notice: 'Transaction was successfully created.'
    else
      render :new
    end
  end

  private

  def set_account
    @account = current_user.accounts.find(params[:account_id])
  end

  def transaction_params
    params.require(:transaction).permit(:amount, :transaction_type, :purpose)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def expenses_for_current_month_for(transactions)
    data = {}
    Transaction::PURPOSES.each do |purpose|
      expenses = transactions.expenses_for(purpose)
      sum = 0
      expenses.each do |amount|
        sum += amount.to_f
      end
      data[purpose.to_sym] = sum
    end
    data
  end

  def current_balance(account)
    data = {}
    data[:withdraws] = account.transactions.where(transaction_type: 'withdraw').pluck(:amount).sum.to_f
    data[:deposits] = account.transactions.where(transaction_type: 'deposit').pluck(:amount).sum.to_f
    data
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def translate_transaction_types
    Transaction::TRANSACTION_TYPES.map do |type|
      [t("transaction.transaction_types.#{type}"), type]
    end
  end

  def translate_purposes
    Transaction::PURPOSES.map do |purpose|
      [t("transaction.purposes.#{purpose}"), purpose]
    end
  end
end

app/views/accounts/_form.html.erb
<%= simple_form_for(@account) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :account_name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/accounts/_modal_transaction.html.erb
<div class="modal" tabindex="-1" role="dialog" id="modal-transaction">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= t('accounts.show.modal.headline') %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <div class="row">
          <dic class="col-md-6">
            <dic class="notification"></div>
          </div>
          <div class="col-md-6">
            <label><%= t('accounts.show.modal.label.amount') %></label>
            <%= text_field_tag :amount, 0.00, id: 'input-amount', class: 'form-control' %>
            <br />
            <label><%= t('accounts.show.modal.label.transaction_type') %></label>
            <%= select_tag :transaction_type, options_for_select(translate_transaction_types), id: 'select-transaction-type', class: 'form-control' %>
            <br />
            <label><%= t('accounts.show.modal.label.purpose') %></label>
            <%= select_tag :purpose, options_for_select(translate_purposes), id: 'select-purpose', class: 'form-control' %>
            <br />
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" id="btn-save"><%= t('buttons.save') %></button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t('buttons.abort') %></button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/accounts/_transactions.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col"><%= t('transactions.date') %></th>
      <th scope="col"><%= t('transactions.transaction_type') %></th>
      <th scope="col"><%= t('transactions.amount') %></th>
      <th scope="col"><%= t('transactions.purpose') %></th>
    </tr>
  </thead>
  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= l transaction.created_at %></td>
        <td><%= t("accounts.transactions.transaction_types.#{transaction.transaction_type}") %></td>
        <td><%= transaction.amount %></td>
        <td><%= t("transaction.purposes.#{transaction.purpose}") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Kontenübersicht</h1>
  <p class="lead">Hier sind alle Deine Konten aufgelistet.</p>
  <hr class="my-4">
  <p>Klicke auf ein Konto, um zur Detailansicht zu gelangen </p>
  <% @accounts.each do |account| %>
    <%= link_to account.account_name, account_path(account), class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<div class="row justify-content-center">
  <div class="col-6">
    <h1><%= t('accounts.show.headline') %></h1>
  </div>
</div>
<br />
<br />
<br />

<% if @account.transactions.any? %>
  <div class="row">
    <div class="col-sm">
      <%= pie_chart expenses_for_current_month_for(@account.transactions.expenses_for_this_month), title: 'Ausgaben in diesem Monat', legend: nil %>
    </div>
    <div class="col-sm">
      <%= pie_chart expenses_for_current_month_for(@account.transactions.all_expenses), title: 'Alle Ausgaben', legend: nil %>
    </div>
    <div class="col-sm">
      <%= pie_chart current_balance(@account), title: 'Aktuelle Bilanz', legend: nil %>
    </div>
  </div>
  <br />
<% end %>

<%= button_tag :new_transaction, class: 'btn btn-primary', id: 'btn-new-transaction' do %>
  <%= t('buttons.new_transaction') %>
<% end %>
<p></p>

<%= render partial: 'transactions', locals: { account: @account } %>

<div class="row">
  <div class="col-auto mr-auto"></div>
  <div class="col-auto"><strong><%= t('accounts.show.balance') %> <%= number_to_currency(@account.balance, precision: 2, unit: '€', seperator: '') %></strong></div>
</div>

<%= link_to t('buttons.back'), accounts_path %>

<%= content_tag :div, class: "parameters", data: {account_id: @account.id} do %>
<% end %>
<%= render partial: 'modal_transaction' %>
<br />

<%= javascript_include_tag 'accounts/show' %>

<script>
  $(document).ready(function() {
    Show.init();
  });
</script>
<%= yield :charts_js %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


  </head>

  <body>
    <div class="container">
    <% if alert  %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
      <% end %>
      <% if notice %>
        <div class="alert alert-primary" role="alert">
          <%= notice %>
        </div>
      <% end %>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">ItsJustMyApp</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <%= link_to 'Kontenübersicht', accounts_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Neues Konto anlegen', new_account_path, class: 'nav-link' %>
            </li>
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "#{current_user.first_name} abmelden", destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Anmelden', new_user_session_path, class: 'nav-link'  %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
      <br />
      <%= yield %>
    </div>
  </body>
</html>

app/views/transactions/_form.html.erb
<%= simple_form_for([@account, @transaction]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :amount %>
    <%= f.input :transaction_type, collection: Transaction::TRANSACTION_TYPES %>
    <%= f.input :purpose, collection: Transaction::PURPOSES %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', account_path(@account) %>